package message

const (
	ACTOR_CREATE              = "ACTOR_CREATE"
	ACTOR_UPDATE              = "ACTOR_UPDATE"
	ACTOR_UPDATE_SHAPE_CIRCLE = "ACTOR_UPDATE_SHAPE_CIRCLE"
	ACTOR_UPDATE_SHAPE_CONVEX = "ACTOR_UPDATE_SHAPE_CONVEX"
)
